[referee]
ip_address = "224.5.23.1"
port = 10003
packet_size = 65535

[physics]
ball_radius = 0.0215
robot_radius = 0.09
stop_game_distance = 0.55
off_field_tolerance = 0.06
kicking_device_distance = 0.08
minimum_ball_velocity_to_consider_movement = 0.05

[ai]
role_swap_hysteresis = 20
distance_tolerance = 0.015
angle_tolerance = 0.175
min_velocity_threshold = 0.1

[skills.kicking]
max_power = 7.5
optimal_distance = 0.09
enable_distance = 0.15
max_velocity = 6.5
min_velocity = 8
enable_duration = 250
min_angle_to_shoot_to_goal = 0.07
min_angle_to_pass = 0.20
deflect_angle = 0.5
min_angle_to_deflect = 0.14

[skills.dribbling]
max_push_distance = 0.9
behind_ball_distance = 0.30

[control.movement]
max_linear_speed = 2.4
min_linear_speed = 0.0
max_linear_accel = 2.3
max_angular_speed = 5.497787
min_angular_speed = 0
speed_boost = 0.0

[control.pid.linear]
kp = 2.0
ki = 0
kd = 0.0
max_integral = 1.0
#kp = 0.35
#ki = 1
#kd = 0.1
#max_integral = 0.4

[control.pid.angular]
kp = 3.4
ki = 0.0
kd = 0.1
max_integral = 0.5
#kp = 1
#ki = 0.7
#kd = 0.0
#max_integral = 2.5

[control.timing]
max_dt = 0.016666
replan_interval = 0.5
kick_enabled_timeout = 200

[system]
thread_frequency = 60
invalid_id = 0xFF
game_off_max_speed = 0.35
max_robots = 11

[pathplanner.potentialfield]
katt = 4
krep = 0.05
min_rad = 5
threshold = 2.5
epsilon = 0.1

[pathplanner.pflorinho]
ball_repulsive = 0.5
repulsive = 0.15
area_repulsive = 0.25
collision_check_radius = 1.5
robot_collision_radius = 0.4
ball_collision_radius = 0.16
x_shift = -0.5
y_shift = 0.0
factor = 2.0

[pathplanner.starpotential]
threshold = 0.2

[pathplanner.univectorfield]
de = 0.020
kr = 0.005
ko = 1
dmin = 0.05
delta = 0.05
maxIts = 1000
step = 0.05