[referee]
ip_address = "224.5.23.1"
port = 10003
packet_size = 65535

[physics]
ball_radius = 0.0215
robot_radius = 0.09
stop_game_distance = 0.55
off_field_tolerance = 0.06

[ai]
max_roles = 6
role_swap_hysteresis = 20
distance_tolerance = 0.015
angle_tolerance = 0.175
min_velocity_threshold = 0.1

[skills.kicking]
max_power = 7.5
optimal_distance = 0.07
enable_distance = 0.15
max_velocity = 6.5
min_velocity = 2.0
enable_duration = 500

[skills.dribbling]
max_push_distance = 0.9
barrier_distance = 0.3
behind_ball_distance = 0.30
minkowski_distance = 0.1

[control.movement]
max_linear_speed = 2.4
min_linear_speed = 0.0
max_linear_accel = 2.3
max_angular_speed = 5.497787
min_angular_speed = 0
linear_error = 0.015
angular_error = 4

[control.pid.linear]
kp = 2.1
ki = 0.01  # New integral term
kd = 0.005
max_integral = 1.0  # Anti-windup

[control.pid.angular]
kp = 0.003
ki = 0.001  # New integral term
kd = 0.0
max_integral = 0.5  # Anti-windup

[control.timing]
max_dt = 0.020
replan_interval = 0.5

[system]
thread_frequency = 60
invalid_id = 0xFF
game_off_max_speed = 0.35
max_robots = 11
bezier_control_point = 2.0